---
  - src: git@github.com:AlexeySetevoi/ansible-clickhouse.git
    scm: git
    version: "1.13"
    name: clickhouse 

  - src: git@github.com:cpskoshel/vector-role.git
    scm: git
    name: vector-role

  - src: git@github.com:cpskoshel/lighthouse-role.git
    scm: git
    name: lighthouse-role
    